# Generated by Django 2.1.2 on 2018-12-31 11:58

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181225_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('catimg', models.FileField(default='CatImg/None/default.svg', upload_to='CatImg/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('1', 'Domestic'), ('2', 'International')], max_length=120)),
                ('country_or_state', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='DestinationCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Destination')),
            ],
            options={
                'verbose_name_plural': 'DestinationCities',
            },
        ),
        migrations.CreateModel(
            name='ItineryInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('inclimg', models.ImageField(default='InclusionImg/None/default.png', upload_to='InclusionImg/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MainInclusions',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagedays', models.PositiveSmallIntegerField(default=1)),
                ('packagenights', models.PositiveSmallIntegerField(default=1)),
                ('packagename', models.CharField(db_index=True, max_length=120, unique=True)),
                ('Overview', models.TextField(default='overview of package')),
                ('actualpriceperperson', models.PositiveIntegerField(default=1)),
                ('offeredpriceperperson', models.PositiveIntegerField(default=1)),
                ('bannerimage', models.ImageField(default='Package/None/default.png', upload_to=crm.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='crm.Category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Destination')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PackageInclusionAndExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('isinclusion', models.BooleanField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Package')),
            ],
            options={
                'verbose_name_plural': 'PackageInclusionAndExclusions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('labels', models.TextField(blank=True, null=True)),
                ('image_One', models.ImageField(blank=True, null=True, upload_to=crm.models.itenery_img_location)),
                ('image_Two', models.ImageField(blank=True, null=True, upload_to=crm.models.itenery_img_location)),
                ('image_Three', models.ImageField(blank=True, null=True, upload_to=crm.models.itenery_img_location)),
                ('itinery_inclusion', models.ManyToManyField(to='crm.ItineryInclusion')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Package')),
            ],
            options={
                'verbose_name_plural': 'PackageItinerary',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='maininclusion',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Package'),
        ),
    ]
