# Generated by Django 2.1.2 on 2019-01-02 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181231_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('About', models.TextField(blank=True, null=True)),
                ('Stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_One', models.ImageField(blank=True, null=True, upload_to='package_img')),
                ('image_Two', models.ImageField(blank=True, null=True, upload_to='package_img')),
                ('image_Three', models.ImageField(blank=True, null=True, upload_to='package_img')),
            ],
            options={
                'verbose_name_plural': 'PackageHotel',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusionandexclusion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineryinclusion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='Overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='actualpriceperperson',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(blank=True, to='crm.Category'),
        ),
        migrations.AlterField(
            model_name='package',
            name='offeredpriceperperson',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagedays',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagenights',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageinclusionandexclusion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='itinery_inclusion',
            field=models.ManyToManyField(blank=True, to='crm.ItineryInclusion'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cabdetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='flightcost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='flightdetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='landpackagecost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='otherenfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='termscond',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='visacost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagehotel',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Package'),
        ),
    ]
