# Generated by Django 2.1.2 on 2019-01-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190102_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspnetrolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.IntegerField()),
                ('roleid', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='aspnetrolepermissions',
            name='Permissions',
            field=models.ManyToManyField(blank=True, to='crm.Permission'),
        ),
    ]
