# Generated by Django 2.1.2 on 2019-01-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190102_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AspnetrolePermissions',
            new_name='AspnetrolePermission',
        ),
        migrations.AlterModelOptions(
            name='aspnetrolepermission',
            options={'verbose_name_plural': 'AspnetrolePermissions'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'Permissions'},
        ),
    ]
