# Generated by Django 2.1.2 on 2019-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190102_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Overview',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='packagehotel',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='packagehotel',
            old_name='image_One',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='packagehotel',
            old_name='image_Three',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='packagehotel',
            old_name='image_Two',
            new_name='image_two',
        ),
        migrations.RenameField(
            model_name='packagehotel',
            old_name='Stars',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='packageitinerary',
            old_name='image_One',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='packageitinerary',
            old_name='image_Three',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='packageitinerary',
            old_name='image_Two',
            new_name='image_two',
        ),
        migrations.AddField(
            model_name='packageinclusionandexclusion',
            name='isexclusion',
            field=models.BooleanField(default=True),
        ),
    ]
