# Generated by Django 2.1.2 on 2019-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_agentleadstatus_assignedagentlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agentid',
            field=models.CharField(default='b438b45b-e2ed-43cb-b65e-7fc109cde71e', max_length=100),
        ),
    ]
