# Generated by Django 2.1.2 on 2019-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_package_agentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='agentid',
            field=models.CharField(max_length=100),
        ),
    ]
