# Generated by Django 2.1.2 on 2019-01-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190105_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.IntegerField(primary_key=True, serialize=False)),
                ('agentid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('companyname', models.CharField(max_length=256)),
                ('createddatetime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='country_or_state',
            new_name='name',
        ),
    ]
