# Generated by Django 2.1.2 on 2019-01-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20190105_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='category',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Category'),
        ),
    ]
