# Generated by Django 2.1.2 on 2019-01-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20190105_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
