# Generated by Django 2.1.2 on 2019-01-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190105_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='destination',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.Destination'),
        ),
    ]
